[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc = "0.8.20"
optimizer = true
via_ir = true

[profile.permit2]
src = "permit2"
solc = "0.8.17"
test = "permit2"
script ="permit2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
